services:

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      CLUSTER_NAME: hive-cluster
    ports:
      - "9870:9870"
    volumes:
      - namenode:/hadoop/dfs/name
    networks:
      - hive-net

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    depends_on:
      - namenode
    volumes:
      - datanode:/hadoop/dfs/data
    networks:
      - hive-net

  hive-metastore-db:
    image: postgres:13
    container_name: metastore-db
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - metastore-db:/var/lib/postgresql/data
    networks:
      - hive-net

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_METASTORE_DB_HOST: metastore-db
      HIVE_METASTORE_DB_NAME: metastore
      HIVE_METASTORE_DB_USER: hive
      HIVE_METASTORE_DB_PASS: hive
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    depends_on:
      - hive-metastore-db
      - namenode
    ports:
      - "9083:9083"
    networks:
      - hive-net

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    environment:
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"
    networks:
      - hive-net

volumes:
  namenode:
  datanode:
  metastore-db:


networks:
  hive-net:
